--TSQL KOMUTLARI--

-------------------- DDL KOMUTLARI -----------------------

--CREATE DATABASE TEST1
--CREATE TABLE ISIMLER (ID INT IDENTITY(1,1), ISIM VARCHAR(20))
--INSERT INTO ISIMLER (ISIM) VALUES ('ÖMER')

--SELECT * FROM ISIMLER

--DROP TABLE ISIMLER

--ALTER TABLE ISIMLER ADD TELEFON VARCHAR(12)
--ALTER TABLE ISIMLER ADD ADRES VARCHAR(500)

--ALTER TABLE ISIMLER DROP COLUMN ADRES

--ALTER TABLE ISIMLER ALTER COLUMN ISIM VARCHAR(50)

------------------ TSQLDE DEGISKEN KULLANIMI ------------------

--DECLARE @ISIM AS VARCHAR(100)
--SELECT @ISIM 

--DECLARE @ISIM AS VARCHAR(100)='ÖMER'
--SELECT @ISIM 

--DECLARE @ISIM AS VARCHAR(100)
--SET @ISIM='ÖMER'
--SELECT @ISIM 


--DECLARE @SAYI1 AS INTEGER
--SET @SAYI1=15
--DECLARE @SAYI2 AS INTEGER
--SET @SAYI2=20
--DECLARE @TOPLAM AS INTEGER
--SET @TOPLAM=@SAYI1+@SAYI2
--SELECT @SAYI1 AS SAYI, @SAYI2 AS SAYI2, @TOPLAM AS TOPLAM

--SELECT * FROM ISIMLER

--DECLARE @ISIM AS VARCHAR(100)
--DECLARE @TELEFON AS VARCHAR(100)


--SELECT
--@ISIM=ISIM, @TELEFON=TELEFON 
--FROM ISIMLER WHERE ID=1
--SELECT @ISIM,@TELEFON

--DECLARE @TARIH AS DATETIME
--SET @TARIH=GETDATE()
--SELECT @TARIH

--------------------- STRING FONKSIYONLAR --------------------

--SUBSTRING FONKSIYONU

--DECLARE @KELIME AS VARCHAR(100)
--SET @KELIME='MERHABA DÜNYA'
--SELECT SUBSTRING(@KELIME,9,5)   --> DUNYA

--LOWER,UPPER FONKSIYONLARI--

--DECLARE @KELIME AS VARCHAR(100)
--SET @KELIME='MERHABA DÜNYA'
--SELECT LOWER(@KELIME)            -->merhaba dünya

--DECLARE @KELIME AS VARCHAR(100)
--SET @KELIME='merhaba dünya'
--SELECT UPPER(@KELIME)            -->MERHABA DÜNYA

--STRING BÝRLEÞTÝRME--

--DECLARE @AD AS VARCHAR(100)='ÖMER'
--DECLARE @SOYAD AS VARCHAR(100)='ÇOLAKOÐLU'
--SELECT @AD+' '+@SOYAD      -->ÖMER ÇOLAKOÐLU

--RIGHT, LEFT FONKSIYONLARI--

--DECLARE @KELIME AS VARCHAR(100)
--SET @KELIME='MERHABA DÜNYA'
--SELECT LEFT(@KELIME,10) --> MERHABA DÜ

--DECLARE @KELIME AS VARCHAR(100)
--SET @KELIME='MERHABA DÜNYA'
--SELECT RIGHT(@KELIME,5) --> DÜNYA

--LTRIM,RTRIM,TRIM FONKSIYONLARI -->boþluklarý siler

--DECLARE @KELIME AS VARCHAR(100)='    MERHABA DÜNYA   '
--SELECT LTRIM(@KELIME) -->soldaki boþluðu temizledi

--DECLARE @KELIME AS VARCHAR(100)='    MERHABA DÜNYA    '
--SELECT RTRIM(@KELIME) -->sagdaki boþluðu temizledi

--DECLARE @KELIME AS VARCHAR(100)='    MERHABA DÜNYA    '
--SELECT TRIM(@KELIME) -->tüm boþluklarý temizledi

--REPLACE FONKSIYONU-- 

--DECLARE @KELIME AS VARCHAR(100)='MERHABA DÜNYA'
--SELECT REPLACE(REPLACE(@KELIME,'MERHABA','HELLO'),'DÜNYA','WORLD')   --> HELLO WORLD

--LEN FONKSIYONU-- uzunluk

--DECLARE @KELIME AS VARCHAR(100)='MERHABA DÜNYA'
--SELECT LEN(@KELIME)  --> 13

--STRING_SPLIT FONKSIYONU-- tablo olarak döndürüyor 

--DECLARE @KELIME AS VARCHAR(100)='BTK AKADEMÝ SQL SERVER EÐÝTÝMÝ'
--SELECT
--* FROM string_split(@KELIME,' ') 

----------------------- DATETIME FONKSIYONLARI -------------------

--DATEADD-- 

--DECLARE @TARIH AS DATETIME
--SET @TARIH='2022-01-20 00:00:00'
--DECLARE @TARIH2 AS DATETIME
--SET @TARIH2=DATEADD(MONTH,39,@TARIH)
--SELECT @TARIH,@TARIH2

--DATEDIFF--  iki tarih arasý fark

--DECLARE @TARIH AS DATETIME
--SET @TARIH='2022-01-20 00:00:00'
--DECLARE @TARIH2 AS DATETIME
--SET @TARIH2='2025-04-16 00:00:00'
--SELECT DATEDIFF(WEEK,@TARIH,@TARIH2)

--DATEFROMPARTS--

--DECLARE @TARIH AS DATETIME
--SET @TARIH=DATEFROMPARTS(2025,4,16)
--SELECT @TARIH

--DATEPART--

--DECLARE @TARIH AS DATETIME
--SET @TARIH='2022-01-20 00:00:00'
--SELECT DATEPART(YEAR,@TARIH)    --> 2022

--DECLARE @TARIH AS DATETIME
--SET @TARIH='2025-04-16 00:00:00'
--SELECT DATEPART(DW,@TARIH)  --> haftanýn kacýncý gunu?

--GETDATE()--

--SELECT GETDATE()  --> suanki zaman

--DECLARE @TARIH AS DATE
--SET @TARIH='1990-12-25'
--SELECT DATEDIFF(YEAR,@TARIH,GETDATE())  --> yas hesaplama

------------------------ DONGULER  ------------------------

--DECLARE @I AS INT=0
--WHILE @I<10
--BEGIN
--SELECT @I
--SET @I=@I+1
--END

--DECLARE @I AS INT=0
--WHILE @I<10
--BEGIN
--PRINT @I
--SET @I=@I+1
--END

--DECLARE @I AS INT=0
--WHILE @I<10
--BEGIN
--	INSERT INTO TARIHLER (TARIH) VALUES (GETDATE())
--	WAITFOR DELAY '00:00:01'
--	SET @I=@I+1
--END

------------------------------------------------------------------

--SELECT * FROM ISIMLER
--SELECT * FROM SOYISIMLER
--SELECT * FROM KISILER


--DECLARE @I AS INT=0
--DECLARE @AD AS VARCHAR(50)
--DECLARE @SOYAD AS VARCHAR(50)
--DECLARE @CINSIYET AS VARCHAR(1)
--DECLARE @DOGUMTARIHI AS DATE
--DECLARE @YAS AS INT
--DECLARE @YASGRUBU AS VARCHAR(30)

--WHILE @I<1000
--BEGIN
--SELECT @AD=AD , @CINSIYET=CINSIYET FROM ISIMLER WHERE ID=ROUND(RAND()*611,0)
--SELECT @SOYAD=SOYAD FROM SOYISIMLER WHERE ID=ROUND(RAND()*1000,0)
--SET @DOGUMTARIHI=DATEADD(DAY,ROUND(RAND()*18250,0),'1950-01-01')
--SET @YAS=DATEDIFF(YEAR,@DOGUMTARIHI,GETDATE())

--IF @YAS BETWEEN 10 AND 20
--SET @YASGRUBU='20 YAÞ ALTI'
--IF @YAS BETWEEN 21 AND 30
--SET @YASGRUBU='20-30 ARASI'
--IF @YAS BETWEEN 31 AND 40
--SET @YASGRUBU='30-40 ARASI'
--IF @YAS BETWEEN 41 AND 50
--SET @YASGRUBU='40-50 ARASI'
--IF @YAS BETWEEN 51 AND 60
--SET @YASGRUBU='50-60 ARASI'
--IF @YAS>60
--SET @YASGRUBU='60 TAN BÜYÜK'

----SELECT @AD,@SOYAD,@CINSIYET,@DOGUMTARIHI,@YAS,@YASGRUBU

--INSERT INTO KISILER (AD,SOYAD,CINSIYET,YAS,YASGRUBU,DOGUMTARIHI)
--VALUES (@AD,@SOYAD,@CINSIYET,@YAS,@YASGRUBU,@DOGUMTARIHI)

--SET @I=@I+1
--END
--
