--TSQL KOMUTLARI--
--DDL KOMUTLARI--

--CREATE DATABASE TEST1
--CREATE TABLE ISIMLER (ID INT IDENTITY(1,1), ISIM VARCHAR(20))
--INSERT INTO ISIMLER (ISIM) VALUES ('ÖMER')

--SELECT * FROM ISIMLER

--DROP TABLE ISIMLER

--ALTER TABLE ISIMLER ADD TELEFON VARCHAR(12)
--ALTER TABLE ISIMLER ADD ADRES VARCHAR(500)

--ALTER TABLE ISIMLER DROP COLUMN ADRES

--ALTER TABLE ISIMLER ALTER COLUMN ISIM VARCHAR(50)

--TSQLDE DEGISKEN KULLANIMI--

--DECLARE @ISIM AS VARCHAR(100)
--SELECT @ISIM 

--DECLARE @ISIM AS VARCHAR(100)='ÖMER'
--SELECT @ISIM 

--DECLARE @ISIM AS VARCHAR(100)
--SET @ISIM='ÖMER'
--SELECT @ISIM 


--DECLARE @SAYI1 AS INTEGER
--SET @SAYI1=15
--DECLARE @SAYI2 AS INTEGER
--SET @SAYI2=20
--DECLARE @TOPLAM AS INTEGER
--SET @TOPLAM=@SAYI1+@SAYI2
--SELECT @SAYI1 AS SAYI, @SAYI2 AS SAYI2, @TOPLAM AS TOPLAM

--SELECT * FROM ISIMLER

--DECLARE @ISIM AS VARCHAR(100)
--DECLARE @TELEFON AS VARCHAR(100)


--SELECT
--@ISIM=ISIM, @TELEFON=TELEFON 
--FROM ISIMLER WHERE ID=1
--SELECT @ISIM,@TELEFON

--DECLARE @TARIH AS DATETIME
--SET @TARIH=GETDATE()
--SELECT @TARIH

--STRING FONKSIYONLAR--

--SUBSTRING FONKSIYONU

--DECLARE @KELIME AS VARCHAR(100)
--SET @KELIME='MERHABA DÜNYA'
--SELECT SUBSTRING(@KELIME,9,5)   --> DUNYA

--LOWER,UPPER FONKSIYONLARI--

--DECLARE @KELIME AS VARCHAR(100)
--SET @KELIME='MERHABA DÜNYA'
--SELECT LOWER(@KELIME)            -->merhaba dünya

--DECLARE @KELIME AS VARCHAR(100)
--SET @KELIME='merhaba dünya'
--SELECT UPPER(@KELIME)            -->MERHABA DÜNYA

--STRING BÝRLEÞTÝRME--

--DECLARE @AD AS VARCHAR(100)='ÖMER'
--DECLARE @SOYAD AS VARCHAR(100)='ÇOLAKOÐLU'
--SELECT @AD+' '+@SOYAD      -->ÖMER ÇOLAKOÐLU

--RIGHT, LEFT FONKSIYONLARI--

--DECLARE @KELIME AS VARCHAR(100)
--SET @KELIME='MERHABA DÜNYA'
--SELECT LEFT(@KELIME,10) --> MERHABA DÜ

--DECLARE @KELIME AS VARCHAR(100)
--SET @KELIME='MERHABA DÜNYA'
--SELECT RIGHT(@KELIME,5) --> DÜNYA

--LTRIM,RTRIM,TRIM FONKSIYONLARI -->boþluklarý siler

--DECLARE @KELIME AS VARCHAR(100)='    MERHABA DÜNYA   '
--SELECT LTRIM(@KELIME) -->soldaki boþluðu temizledi

--DECLARE @KELIME AS VARCHAR(100)='    MERHABA DÜNYA    '
--SELECT RTRIM(@KELIME) -->sagdaki boþluðu temizledi

--DECLARE @KELIME AS VARCHAR(100)='    MERHABA DÜNYA    '
--SELECT TRIM(@KELIME) -->tüm boþluklarý temizledi

--REPLACE FONKSIYONU-- 

--DECLARE @KELIME AS VARCHAR(100)='MERHABA DÜNYA'
--SELECT REPLACE(REPLACE(@KELIME,'MERHABA','HELLO'),'DÜNYA','WORLD')   --> HELLO WORLD

--LEN FONKSIYONU-- uzunluk

--DECLARE @KELIME AS VARCHAR(100)='MERHABA DÜNYA'
--SELECT LEN(@KELIME)  --> 13

--STRING_SPLIT FONKSIYONU-- tablo olarak döndürüyor 

--DECLARE @KELIME AS VARCHAR(100)='BTK AKADEMÝ SQL SERVER EÐÝTÝMÝ'
--SELECT
--* FROM string_split(@KELIME,' ') 