--SET STATISTICS IO ON
--SELECT * FROM CUSTOMERS
--WHERE NAMESURNAME = 'ÖMER ÇOLAKOÐLU'

--SP_SPACEUSED 'CUSTOMERS'

--SELECT * FROM CUSTOMERS WHERE ID=168483

--SET STATISTICS IO ON
--SELECT * FROM CUSTOMERS
--WHERE TELNR='03423344747'

--SET STATISTICS IO ON 
--SELECT * FROM CUSTOMERS WHERE TELNR='03423344747' AND NAMESURNAME='ÖMER ÇOLAKOÐLU'   -- IX1 indexini kullandý.

--SET STATISTICS IO ON 
--SELECT * FROM CUSTOMERS WHERE TELNR='03423344747' OR NAMESURNAME='ÖMER ÇOLAKOÐLU'    -- IX1 ve IX2 indexlerini kullandý

--SET STATISTICS IO ON 
--SELECT * FROM CUSTOMERS
--WHERE BIRTHDATE='1964-03-30'    -- IX3 kullandý

--SET STATISTICS IO ON 
--SELECT * FROM CUSTOMERS 
--WHERE BIRTHDATE='1964-03-30' AND NAMESURNAME='ÖMER ÇOLAKOÐLU'      -- IX1 kullandý

--SET STATISTICS IO ON
--SELECT * FROM CUSTOMERS WHERE TCNO='10019865823'

--SELECT * FROM CUSTOMERS WHERE ID=35578 
--UPDATE CUSTOMERS SET TCNO='10019865823' WHERE ID=35578  -- hata verdi, tekrarlayan veri kullanýlamaz

