--SELECT * FROM USERS
--SELECT * FROM TOWNS
--SELECT * FROM COUNTRIES
--SELECT * FROM DISTRICTS
--SELECT * FROM CITIES
--SELECT * FROM ADDRESS

--SELECT * FROM USERS WHERE ID=1
--SELECT * FROM ADDRESS WHERE USERID=1

--SELECT USERS.*, ADDRESS.ADDRESSTEXT FROM 
--USERS, ADDRESS
--WHERE USERS.ID=ADDRESS.USERID
--AND USERS.ID=1

--SELECT 
--U.NAMESURNAME AS AD_SOYAD,
--U.EMAIL MAIL_ADRESI,
--U.GENDER CINSIYET, 
--U.BIRTHDATE DOGUM_TARIHI,
--A.ADDRESSTEXT AS ACIK_ADRES
--FROM 
--USERS U, ADDRESS A
--WHERE U.ID=A.USERID
--AND U.ID=4