--ASCII VE CHAR FONKSIYONLARI

--SELECT ASCII ('A') --> 65
--SELECT ASCII ('Ö') --> 214
--SELECT ASCII ('3') --> 51
--SELECT CHAR(214) --> Ö
--SELECT ASCII('1') --> 49
--SELECT CHAR(49)  --> 1
--SELECT ASCII(CHAR(49)) --> 49
--SELECT CHAR(ASCII('Ö')) --> Ö
--SELECT ASCII('?') --> 63
--SELECT CHAR(63) --> ?

--SUBSTRING FONKSIYONU

--SELECT SUBSTRING('ÝREM ÖZDEMÝR',1,4) --> 1.karakterden itibaren 4 karakter alýyor.
--SELECT * FROM USERS WHERE USERNAME_ LIKE 'O%' --> kullanýcý adý O ile baþlayanlar
--SELECT * FROM USERS WHERE SUBSTRING(USERNAME_,1,1)='O' --> ilk harfi O olanlar
--SELECT * FROM USERS WHERE USERNAME_ LIKE '%O' --> kullanýcý adý O ile bitenler
--SELECT * FROM USERS WHERE SUBSTRING(USERNAME_,LEN(USERNAME_),1)='O' --> son harfi O olanlar
--SELECT LEN('A_KALKMAZO')
--SELECT SUBSTRING('A_KALKMAZO',10,1)

--CHARINDEX 

--SELECT CHARINDEX('D','ÝREM ÖZDEMÝR',1) --> 8
--SELECT CHARINDEX('Ð','ÝREM ÖZDEMÝR',1) --> 0

--CONCAT

--SELECT 'ÝREM'+'ÖZDEMÝR' -->ÝREMÖZDEMÝR
--SELECT CONCAT('ÖMER',' ','FARUK',' ','ÇOLAKOÐLU') --> ÖMER FARUK ÇOLAKOÐLU
--SELECT CONCAT_WS(' ','ÖMER','FARUK','ÇOLAKOÐLU') --> ÖMER FARUK ÇOLAKOÐLU

--SELECT 
--USERNAME_ + ' ' + PASSWORD_ + ' ' + NAMESURNAME,
--CONCAT(USERNAME_ , ' ' , PASSWORD_ , ' ' , NAMESURNAME),
--CONCAT_WS(' ',USERNAME_ , PASSWORD_ ,NAMESURNAME),
--* FROM USERS