--SELECT * FROM COUNTRIES
--SELECT * FROM CITIES

--DELETE FROM COUNTRIES WHERE ID=9
--DELETE FROM CITIES WHERE COUNTRYID=9

--SELECT * FROM COUNTRIES
--SELECT * FROM CITIES

--DELETE FROM COUNTRIES WHERE ID=8

--DELETE FROM CITIES WHERE ID=13

--DELETE FROM COUNTRIES WHERE ID=5

--CREATE TABLE TEST (ID INT IDENTITY(1,1), CUSTOMERNAME VARCHAR(60))

--DROP TABLE TEST