--SELECT * FROM SALES
--SELECT COUNT(*) FROM SALES     // satýr sayýsýný getirdi.
--SELECT * FROM SALES ORDER BY AMOUNT     // miktara göre azdan çoka sýraladý
--SELECT MIN(AMOUNT),MAX(AMOUNT),COUNT(FICHENO) FROM SALES 
--SELECT SUM(AMOUNT) FROM SALES     // toplam kaç ürün satýldý?
--SELECT AVG(AMOUNT) FROM SALES     // 1 satýþta ort kaç ürün satýldý?
--SELECT * FROM SALES ORDER BY TOTALPRICE
--SELECT MIN(TOTALPRICE),MAX(TOTALPRICE),COUNT(FICHENO),SUM(TOTALPRICE),AVG(TOTALPRICE) 
--FROM SALES WHERE CITY='MUÐLA'

-- GROUP BY KOMUTU 

--SELECT CITY, 
--MIN(TOTALPRICE) AS MINPRICE,
--MAX(TOTALPRICE) AS MAXPRICE,
--COUNT(FICHENO) AS ROWCOUNT_,
--SUM(TOTALPRICE) AS TOTALPRICE,
--AVG(TOTALPRICE) AS AVGPRICE
--FROM SALES 
--GROUP BY CITY 
--ORDER BY CITY

--SELECT TOP 10 CITY,
--SUM(TOTALPRICE) AS TOTALPRICE
--FROM SALES
--GROUP BY CITY
--ORDER BY SUM(TOTALPRICE) DESC   --en çok satýþ yapan ÝLK 10 maðazayý çoktan aza sýraladý

--Bir maðazanýn gün bazlý satýþ rakamlarýný getirme

--SELECT *,
--CONVERT(date,DATE_) AS DATE2
--FROM SALES WHERE CITY='ANKARA' 
--ORDER BY DATE_

--UPDATE SALES SET DATE2=CONVERT(date,DATE_)

--SELECT CITY,DATE2,SUM(TOTALPRICE) AS TOTALPRICE FROM SALES WHERE CITY='ANKARA' 
--GROUP BY CITY,DATE2
--ORDER BY CITY,DATE2

--Bir Günün Maðaza Bazlý Satýþ Rakamlarýný Getirme

--SELECT * FROM SALES WHERE DATE2='2019-01-01'

--SELECT DATE2,CITY,SUM(TOTALPRICE) AS TOTALPRICE FROM SALES 
--WHERE DATE2='2019-01-01'
--GROUP BY DATE2,CITY
--ORDER BY DATE2,SUM(TOTALPRICE)DESC

--Maðazalarýn Aylara Göre Satýþ Rakamlarýný Getirme

--SELECT * FROM SALES

--UPDATE SALES SET MONTHNAME_='01.OCAK' WHERE DATEPART(MONTH,DATE2)=1
--UPDATE SALES SET MONTHNAME_='02.ÞUBAT' WHERE DATEPART(MONTH,DATE2)=2
--UPDATE SALES SET MONTHNAME_='03.MART' WHERE DATEPART(MONTH,DATE2)=3
--UPDATE SALES SET MONTHNAME_='04.NÝSAN' WHERE DATEPART(MONTH,DATE2)=4
--UPDATE SALES SET MONTHNAME_='05.MAYIS' WHERE DATEPART(MONTH,DATE2)=5
--UPDATE SALES SET MONTHNAME_='06.HAZÝRAN' WHERE DATEPART(MONTH,DATE2)=6
--UPDATE SALES SET MONTHNAME_='07.TEMMUZ' WHERE DATEPART(MONTH,DATE2)=7
--UPDATE SALES SET MONTHNAME_='08.AÐUSTOS' WHERE DATEPART(MONTH,DATE2)=8
--UPDATE SALES SET MONTHNAME_='09.EYLÜL' WHERE DATEPART(MONTH,DATE2)=9
--UPDATE SALES SET MONTHNAME_='10.EKÝM' WHERE DATEPART(MONTH,DATE2)=10
--UPDATE SALES SET MONTHNAME_='11.KASIM' WHERE DATEPART(MONTH,DATE2)=11
--UPDATE SALES SET MONTHNAME_='12.ARALIK' WHERE DATEPART(MONTH,DATE2)=12

--SELECT MONTHNAME_,SUM(TOTALPRICE) AS TOTALPRICE FROM SALES 
--GROUP BY MONTHNAME_
--ORDER BY MONTHNAME_

--Sehirlerin aylara gore dagilimi;

--SELECT CITY,MONTHNAME_,SUM(TOTALPRICE) AS TOTALPRICE FROM SALES 
--GROUP BY CITY,MONTHNAME_
--ORDER BY CITY,MONTHNAME_

--En cok satis yapan illere gore siralama;

--SELECT MONTHNAME_,CITY,SUM(TOTALPRICE) AS TOTALPRICE FROM SALES 
--GROUP BY CITY,MONTHNAME_
--ORDER BY MONTHNAME_,SUM(TOTALPRICE) DESC

--Urun kategorilerine gore satis rakamlarini getirme;

--SELECT CATEGORY1,CATEGORY2,CATEGORY3,CATEGORY4,
--SUM(TOTALPRICE) AS TOTALPRICE,
--COUNT(*) AS ROWCOUNT_,
--SUM(AMOUNT) AS TOTALAMOUNT
--FROM SALES 
--GROUP BY CATEGORY1,CATEGORY2,CATEGORY3,CATEGORY4
--ORDER BY CATEGORY1,CATEGORY2,CATEGORY3,CATEGORY4

--Maðazalarýn müþteri sayýlarýný getirme;

--SELECT
--CITY,FICHENO,COUNT(*)
--FROM SALES WHERE MONTHNAME_='01.OCAK'
--AND CITY='ADANA'
--GROUP BY CITY, FICHENO

--SELECT
--CITY,COUNT(DISTINCT FICHENO),COUNT(*)
--FROM SALES WHERE MONTHNAME_='01.OCAK'
--GROUP BY CITY
--ORDER BY CITY

--SELECT
--CITY,COUNT(DISTINCT CUSTOMERNAME) AS UNIQUECUSTOMER,
--COUNT(DISTINCT FICHENO) CUSTOMERCOUNT,
--COUNT(*) ITEMCOUNT
--FROM SALES WHERE MONTHNAME_='01.OCAK'

--GROUP BY CITY
--ORDER BY CITY

--Belli bir cironun uzerinde satis yapan magazalari getirme;

--SELECT CITY,SUM(TOTALPRICE)
--FROM SALES
--GROUP BY CITY
--HAVING SUM(TOTALPRICE)>40000
--ORDER BY SUM(TOTALPRICE) DESC

--Belli bir sayinin uzerindeki tekil musterileri getirme;

--SELECT CITY,SUM(TOTALPRICE) AS TOTALPRICE,
--COUNT(DISTINCT CUSTOMERNAME) CUSTOMERCOUNT
--FROM SALES
--GROUP BY CITY
--HAVING COUNT(DISTINCT CUSTOMERNAME)>3000
--ORDER BY SUM(TOTALPRICE) DESC

--SELECT * FROM CUSTOMERS2
--INSERT INTO CUSTOMERS2
--(NAME1,NAME2,NAME3,NAME4,NAME5,NAME6,NAME7,NAME8)
--VALUES
--('ÖMER','ÖMER','ÖMER','ÖMER','ÖMER','ÖMER','ÖMER','ÖMER')

--SELECT NAME1,NAME2,NAME3,NAME4,NAME5,NAME6,NAME7,NAME8 FROM CUSTOMERS2



                                                                      
																	  
