--USE ETRADE
--SELECT[ID], [CUSTOMERNAME], [CITY], [BIRTHDATE], [DISTRICT], [GENDER]
--FROM CUSTOMERS

--TEMEL SQL KOMUTLARI

--INSERT INTO CUSTOMERS
--(CUSTOMERNAME,CITY,BIRTHDATE,DISTRICT,GENDER)
--VALUES
--('MEHMET ÖZAL','ANTALYA','1990-12-21','ALANYA','E')

--Select * from CUSTOMERS

--UPDATE CUSTOMERS
--SET NATION='TR'

--UPDATE CUSTOMERS
--SET NATION='TR' , AGE=DATEDIFF(YEAR,BIRTHDATE,GETDATE())

--SELECT * FROM CUSTOMERS
--DELETE FROM CUSTOMERS

--INSERT INTO CUSTOMERS(CUSTOMERNAME,CITY,DISTRICT,BIRTHDATE,GENDER) VALUES ('Volkan ÇEKÝP','Bartýn','Kurucaþile','1997-10-24 00:00:00.000','E')
--SELECT * FROM CUSTOMERS

--TRUNCATE TABLE CUSTOMERS

--SELECT * FROM CUSTOMERS  WHERE CITY='ÝSTANBUL'
--SELECT * FROM CUSTOMERS  WHERE CITY<>'ÝSTANBUL' // <> : eþit deðildir
--SELECT * FROM CUSTOMERS  WHERE BIRTHDATE>'1980-01-01'
--SELECT * FROM CUSTOMERS  WHERE GENDER='K'
--SELECT * FROM CUSTOMERS  WHERE AGE BETWEEN 22 AND 30
--SELECT * FROM CUSTOMERS  WHERE CUSTOMERNAME LIKE 'ÝREM%'   //ile baþlayan
--SELECT * FROM CUSTOMERS  WHERE CUSTOMERNAME LIKE '%HANOÐLU'  //ile biten
--SELECT * FROM CUSTOMERS  WHERE CUSTOMERNAME LIKE '%ALAN%' // içeren  like : ile baþlar/biter/içerir
--SELECT * FROM CUSTOMERS  WHERE CITY IN ('ÝSTANBUL','BURSA')  // in : içinde
--SELECT * FROM CUSTOMERS  WHERE CUSTOMERNAME NOT LIKE 'EMRE%' // not like : ile baþlamaz/bitmez/içermez
--SELECT * FROM CUSTOMERS  WHERE CITY NOT IN ('ÝSTANBUL','BURSA') //not in : içinde olmayan

--Select * from CUSTOMERS
--where CUSTOMERNAME='Irmak TAHSÝNOÐLU'

--UPDATE CUSTOMERS SET GENDER='ERKEK' WHERE GENDER='E'
--UPDATE CUSTOMERS SET GENDER='KADIN' WHERE GENDER='K'

--DELETE FROM CUSTOMERS WHERE ID=19

--AND/OR KOMUTLARI

--SELECT * FROM CUSTOMERS
--WHERE CITY='ÝSTANBUL' AND DISTRICT='BEYLÝKDÜZÜ'
--AND DISTRICT='ESENLER'  // hem esenler hem beylikdüzü olamaz 0 sonuç

--SELECT * FROM CUSTOMERS
--WHERE CITY='ÝSTANBUL' AND GENDER='ERKEK'
--AND DISTRICT='ESENLER'

--SELECT * FROM CUSTOMERS
--WHERE CITY='ÝSTANBUL' AND GENDER='ERKEK'
--AND BIRTHDATE BETWEEN '19900101' AND '20000101'

--SELECT * FROM CUSTOMERS
--WHERE CITY='ÝSTANBUL' OR CITY='ÝZMÝR'

--SELECT * FROM CUSTOMERS
--WHERE CITY IN ('ÝSTANBUL','ÝZMÝR','BURSA')

--SELECT * FROM CUSTOMERS
--WHERE
--CITY='ÝSTANBUL' OR CITY='ÝZMÝR' OR CITY='BURSA'

--SELECT * FROM CUSTOMERS
--WHERE BIRTHDATE BETWEEN '19900101' AND '19981231'
--WHERE BIRTHDATE >= '19900101' AND BIRTHDATE <= '19981231'

--WHERE BIRTHDATE <= '19900101' OR BIRTHDATE >= '19981231'
--WHERE NOT BIRTHDATE BETWEEN '19900101' AND '19981231'

--DISTINCT KOMUTU  //Çoklu veriyi tekilleþtirmek için.

--SELECT CITY FROM CUSTOMERS //1000kayýt
--SELECT DISTINCT CITY FROM CUSTOMERS //81kayýt

--SELECT CITY,DISTRICT FROM CUSTOMERS
--WHERE CITY='MUÐLA' //17kayýt
--SELECT DISTINCT CITY,DISTRICT FROM CUSTOMERS
--WHERE CITY='MUÐLA' //9kayýt

--ORDER BY KOMUTU  //Sýralama

--SELECT * FROM CUSTOMERS 
--ORDER BY CUSTOMERNAME

--SELECT * FROM CUSTOMERS 
--ORDER BY CUSTOMERNAME DESC

--SELECT * FROM CUSTOMERS WHERE CITY='ÝSTANBUL'
--ORDER BY CITY,DISTRICT,CUSTOMERNAME  

--SELECT * FROM CUSTOMERS
--WHERE CITY='ÝSTANBUL' ORDER BY 2  //2.kolona göre sýralar

--TOP KOMUTU  //Bir veri setinden dönen kayýtlarýn tamamý yerine bir kýsmýný görmemizi saðlar.

--SELECT TOP 100 * FROM CUSTOMERS  //sadece 100 satýrý getirdi

--SELECT TOP 10 * FROM CUSTOMERS ORDER BY CUSTOMERNAME

--SELECT TOP 50 PERCENT * FROM CUSTOMERS ORDER BY CUSTOMERNAME  //%50sini getirdi

--SELECT TOP 1 * FROM CUSTOMERS ORDER BY CUSTOMERNAME  //1 satýr getirdi

