--SELECT * FROM USERS
--SELECT * FROM TOWNS
--SELECT * FROM COUNTRIES
--SELECT * FROM DISTRICTS
--SELECT * FROM CITIES
--SELECT * FROM ADDRESS

--SELECT * FROM USERS WHERE ID=1
--SELECT * FROM ADDRESS WHERE USERID=1

--SELECT USERS.*, ADDRESS.ADDRESSTEXT FROM 
--USERS, ADDRESS
--WHERE USERS.ID=ADDRESS.USERID
--AND USERS.ID=1

--SELECT 
--U.NAMESURNAME AS AD_SOYAD,
--U.EMAIL MAIL_ADRESI,
--U.GENDER CINSIYET, 
--U.BIRTHDATE DOGUM_TARIHI,
--C.COUNTRY AS ULKE,
--CT.CITY AS SEHIR,
--T.TOWN AS ILCE,
--D.DISTRICT AS SEMT,
--A.POSTALCODE AS POSTAKODU,
--A.ADDRESSTEXT AS ACIK_ADRES
--FROM 
--USERS U, ADDRESS A, COUNTRIES C, CITIES CT, TOWNS T, DISTRICTS D
--WHERE U.ID=A.USERID AND C.ID=A.COUNTRYID AND CT.ID=A.CITYID
--AND T.ID=A.TOWNID AND D.ID=A.DISTRICTID 
----AND U.ID=4
--AND CT.CITY LIKE 'ÝZMÝR'
--ORDER BY U.NAMESURNAME

--SELECT 
--COUNT(U.ID)
--FROM 
--USERS U, ADDRESS A, COUNTRIES C, CITIES CT, TOWNS T, DISTRICTS D
--WHERE U.ID=A.USERID AND C.ID=A.COUNTRYID AND CT.ID=A.CITYID
--AND T.ID=A.TOWNID AND D.ID=A.DISTRICTID 

--SELECT 
--COUNT(U.NAMESURNAME)
--FROM 
--USERS U, ADDRESS A, COUNTRIES C, CITIES CT, TOWNS T, DISTRICTS D
--WHERE U.ID=A.USERID AND C.ID=A.COUNTRYID AND CT.ID=A.CITYID
--AND T.ID=A.TOWNID AND D.ID=A.DISTRICTID 

--SELECT 
--COUNT(DISTINCT U.NAMESURNAME)
--FROM 
--USERS U, ADDRESS A, COUNTRIES C, CITIES CT, TOWNS T, DISTRICTS D
--WHERE U.ID=A.USERID AND C.ID=A.COUNTRYID AND CT.ID=A.CITYID
--AND T.ID=A.TOWNID AND D.ID=A.DISTRICTID 

--SELECT 
--U.NAMESURNAME
--FROM 
--USERS U, ADDRESS A, COUNTRIES C, CITIES CT, TOWNS T, DISTRICTS D
--WHERE U.ID=A.USERID AND C.ID=A.COUNTRYID AND CT.ID=A.CITYID
--AND T.ID=A.TOWNID AND D.ID=A.DISTRICTID 

--SELECT 
--DISTINCT U.NAMESURNAME
--FROM 
--USERS U, ADDRESS A, COUNTRIES C, CITIES CT, TOWNS T, DISTRICTS D
--WHERE U.ID=A.USERID AND C.ID=A.COUNTRYID AND CT.ID=A.CITYID
--AND T.ID=A.TOWNID AND D.ID=A.DISTRICTID 

--SELECT 
--U.NAMESURNAME, COUNT(A.ID) AS ADRESSAYISI, COUNT(DISTINCT C.ID) AS ULKESAYISI,
--COUNT(DISTINCT CT.ID) AS SEHIRSAYISI
--FROM 
--USERS U, ADDRESS A, COUNTRIES C, CITIES CT, TOWNS T, DISTRICTS D
--WHERE U.ID=A.USERID AND C.ID=A.COUNTRYID AND CT.ID=A.CITYID
--AND T.ID=A.TOWNID AND D.ID=A.DISTRICTID 
--GROUP BY U.NAMESURNAME

--SELECT 
--U.NAMESURNAME, COUNT(A.ID) AS ADRESSAYISI, COUNT(DISTINCT C.ID) AS ULKESAYISI,
--COUNT(DISTINCT CT.ID) AS SEHIRSAYISI
--FROM 
--USERS U, ADDRESS A, COUNTRIES C, CITIES CT, TOWNS T, DISTRICTS D
--WHERE U.ID=A.USERID AND C.ID=A.COUNTRYID AND CT.ID=A.CITYID
--AND T.ID=A.TOWNID AND D.ID=A.DISTRICTID 
--GROUP BY U.NAMESURNAME
--HAVING COUNT(A.ID)>2

--SELECT 
--CT.CITY, COUNT(U.ID) AS KULLANICISAYISI, COUNT(DISTINCT D.DISTRICT) AS ILCESAYISI
--FROM 
--USERS U, ADDRESS A, COUNTRIES C, CITIES CT, TOWNS T, DISTRICTS D
--WHERE U.ID=A.USERID AND C.ID=A.COUNTRYID AND CT.ID=A.CITYID
--AND T.ID=A.TOWNID AND D.ID=A.DISTRICTID 
--GROUP BY CT.CITY

--SELECT U.NAMESURNAME,U.EMAIL, A.ADDRESSTEXT, C.COUNTRY, CT.CITY,T.TOWN,D.DISTRICT
--FROM
--USERS U 
--JOIN ADDRESS A ON A.USERID=U.ID
--JOIN COUNTRIES C ON C.ID=A.COUNTRYID
--JOIN CITIES CT ON CT.ID=A.CITYID
--JOIN TOWNS T ON T.ID=A.TOWNID
--JOIN DISTRICTS D ON D.ID=A.DISTRICTID

--SELECT 
--CT.CITY,COUNT(U.ID) AS KULLANICISAYISI
--FROM
--USERS U 
--JOIN ADDRESS A ON A.USERID=U.ID
--JOIN COUNTRIES C ON C.ID=A.COUNTRYID
--JOIN CITIES CT ON CT.ID=A.CITYID
--JOIN TOWNS T ON T.ID=A.TOWNID
--JOIN DISTRICTS D ON D.ID=A.DISTRICTID
--GROUP BY CT.CITY

