--SELECT * FROM SALES
--SELECT COUNT(*) FROM SALES     // satýr sayýsýný getirdi.
--SELECT * FROM SALES ORDER BY AMOUNT     // miktara göre azdan çoka sýraladý
--SELECT MIN(AMOUNT),MAX(AMOUNT),COUNT(FICHENO) FROM SALES 
--SELECT SUM(AMOUNT) FROM SALES     // toplam kaç ürün satýldý?
--SELECT AVG(AMOUNT) FROM SALES     // 1 satýþta ort kaç ürün satýldý?
--SELECT * FROM SALES ORDER BY TOTALPRICE
--SELECT MIN(TOTALPRICE),MAX(TOTALPRICE),COUNT(FICHENO),SUM(TOTALPRICE),AVG(TOTALPRICE) 
--FROM SALES WHERE CITY='MUÐLA'

-- GROUP BY KOMUTU 

--SELECT CITY, 
--MIN(TOTALPRICE) AS MINPRICE,
--MAX(TOTALPRICE) AS MAXPRICE,
--COUNT(FICHENO) AS ROWCOUNT_,
--SUM(TOTALPRICE) AS TOTALPRICE,
--AVG(TOTALPRICE) AS AVGPRICE
--FROM SALES 
--GROUP BY CITY 
--ORDER BY CITY

--SELECT TOP 10 CITY,
--SUM(TOTALPRICE) AS TOTALPRICE
--FROM SALES
--GROUP BY CITY
--ORDER BY SUM(TOTALPRICE) DESC   --en çok satýþ yapan ÝLK 10 maðazayý çoktan aza sýraladý

--Bir maðazanýn gün bazlý satýþ rakamlarýný getirme

--SELECT *,
--CONVERT(date,DATE_) AS DATE2
--FROM SALES WHERE CITY='ANKARA' 
--ORDER BY DATE_

--UPDATE SALES SET DATE2=CONVERT(date,DATE_)

SELECT *
FROM SALES WHERE CITY='ANKARA' 

ORDER BY DATE_
