--SELECT * FROM USERS
--SELECT * FROM ADDRESS
--SELECT * FROM INVOICEDETAILS

--Kullanýcý Adý , Ad Soyad, Ýl, Ýlçe, Semt, Açýk Adres
--Sipariþ ID, Tarih, Toplam Tutar, Ödeme Tarihi
--Banka Onay Kodu, Fatura Tarihi, Kargo Fiþ No

--SELECT
--U.USERNAME_ AS KULLANICIADI,
--U.NAMESURNAME AS ADSOYAD,
--CT.CITY AS IL, T.TOWN AS ILCE, D.DISTRICT AS SEMT, A.ADDRESSTEXT AS
--ACIKADRES, O.ID AS SIPARISID, O.DATE_ AS TARIH, O.TOTALPRICE AS TOPLAMTUTAR, P.DATE_ AS ODEMETARIHI,
--P.APPROVECODE AS BANKAONAYKODU,
--I.DATE_ AS FATURATARIHI, I.CARGOFICHENO AS KARGOFISNO
--FROM ORDERS O
--INNER JOIN USERS U ON U.ID=O.USERID
--INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
--INNER JOIN CITIES CT ON CT.ID=A.CITYID
--INNER JOIN TOWNS T ON T.ID=A.TOWNID
--INNER JOIN DISTRICTS D ON D.ID=A.DISTRICTID
--INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
--INNER JOIN INVOICES I ON I.ORDERID=O.ID

--WHERE U.NAMESURNAME='CEYDA GEZGÝNCÝ'

--SELECT
--U.USERNAME_ AS KULLANICIADI,
--U.NAMESURNAME AS ADSOYAD,
--CT.CITY AS IL, T.TOWN AS ILCE, D.DISTRICT AS SEMT, A.ADDRESSTEXT AS
--ACIKADRES, O.ID AS SIPARISID, O.DATE_ AS TARIH, O.TOTALPRICE AS TOPLAMTUTAR, P.DATE_ AS ODEMETARIHI,
--P.APPROVECODE AS BANKAONAYKODU,
--I.DATE_ AS FATURATARIHI, I.CARGOFICHENO AS KARGOFISNO,
--ITM.ITEMCODE AS URUNKODU, ITM.ITEMNAME AS URUNADI, OD.AMOUNT AS MIKTAR,
--OD.UNITPRICE AS BIRIMFIYAT, OD.LINETOTAL AS SATIRTOPLAMI

--FROM ORDERS O
--INNER JOIN USERS U ON U.ID=O.USERID
--INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
--INNER JOIN CITIES CT ON CT.ID=A.CITYID
--INNER JOIN TOWNS T ON T.ID=A.TOWNID
--INNER JOIN DISTRICTS D ON D.ID=A.DISTRICTID
--INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
--INNER JOIN INVOICES I ON I.ORDERID=O.ID
--INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
--INNER JOIN ITEMS ITM ON ITM.ID=OD.ITEMID
--WHERE --O.ID=26121
----U.NAMESURNAME='CEYDA GEZGÝNCÝ'

--sehirlere gore verilen siparisleri toplam olarak listeleme

--SELECT
--CT.CITY AS SEHIRADI,
--SUM(OD.LINETOTAL) AS TOPLAMSIPARIS_TUTARI,
--SUM(OD.AMOUNT) AS TOPLAMSIPARIS_ADEDI,
--COUNT(OD.ID) AS TOPLAMSIPARIS_SAYISI
--FROM ORDERS O
--INNER JOIN USERS U ON U.ID=O.USERID
--INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
--INNER JOIN CITIES CT ON CT.ID=A.CITYID
--INNER JOIN TOWNS T ON T.ID=A.TOWNID
--INNER JOIN DISTRICTS D ON D.ID=A.DISTRICTID
--INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
--INNER JOIN INVOICES I ON I.ORDERID=O.ID
--INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
--INNER JOIN ITEMS ITM ON ITM.ID=OD.ITEMID

--GROUP BY CT.CITY
----ORDER BY CT.CITY
----ORDER BY SUM(OD.LINETOTAL) DESC
--ORDER BY COUNT(OD.ID) DESC

--urun kategorilerine gore siparis dagilimi

